services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    hostname: mongodb
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    volumes:
      - dbdata6:./data/db
    ports:
      - "27017:27017"
